name: Update MLB Elo Ratings

on:
  schedule:
    - cron: '0 6 * * *'  # 6:00 UTC
  workflow_dispatch:     

jobs:     
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install flask jinja2 requests beautifulsoup4 pytz 
        
    - name: Generate static site
      run: python generate_static_site.py
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        branch: gh-pages

  copy-logos:
    runs-on: ubuntu-latest
    needs: update  # This ensures this job runs after the update job completes
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-branch
          
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages-branch
      
      - name: Copy static folder with team logos
        run: |
          # Create static directory in gh-pages if it doesn't exist
          mkdir -p gh-pages-branch/static
          
          # Copy team logos from main branch to gh-pages
          cp -r main-branch/static/* gh-pages-branch/static/
          
          cd gh-pages-branch
          
          # Set up git config
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
          # Add changes to git
          git add static/
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update MLB team logos from main branch"
            git push
            echo "Team logos updated successfully"
          fi
