name: Update MLB Elo Ratings

on:
  schedule:
    - cron: '0 6 * * *'  # 6:00 UTC
  workflow_dispatch:     

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install flask requests beautifulsoup4 pytz
        
    - name: Run update script
      run: |
        python data.py
        
    - name: Commit and push if changes
      run: |
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update MLB Elo ratings"
        git push
